BOARD="adnrpi1"
BOOTSIZE="512"
BOOTFS_TYPE="fat"
RELEASE="noble"
BUILD_DESKTOP="yes"
DESKTOP_APPGROUPS_SELECTED="browsers"
DESKTOP_ENVIRONMENT=xfce
DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base
PACKAGE_LIST_BOARD="${PACKAGE_LIST_BOARD} onboard lm-sensors xinput x11-xserver-utils"
ADNRPI_ROS="ros2"
ADNRPI_ROS_DESKTOP="yes"
