BOARD="smartpi1"
BOOTSIZE="512"
BOOTFS_TYPE="fat"           # use FAT filesystem for the /boot directory

BRANCH="legacy"
RELEASE="bullseye"
INSTALL_HEADERS="no"        # pahole package does not exist on Bullseye (provided by dwarves)
